cluster.name: my-test
node.name: es
node.master: true
node.data: true

network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
#http.cors.enabled: true
#http.cors.allow-origin: "*"

#discovery.zen.ping.unicast.hosts: ["es:9300", "es1:9300"]
#discovery.zen.minimum_master_nodes: 2
#discovery.zen.ping_timeout: 5s

bootstrap.memory_lock: true
action.destructive_requires_name: true
